# Generated by Django 5.1.3 on 2025-03-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_subject_alter_mark_subject'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='home.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
