# Generated by Django 5.1.6 on 2025-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
