# Generated by Django 5.1.3 on 2025-03-21 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Ваше фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
