# Generated by Django 5.1.3 on 2025-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Твій гітхаб'),
        ),
    ]
