# Generated by Django 5.1.3 on 2025-03-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ins',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на інстаграм'),
        ),
    ]
